### ISSUE TITLE
panvimdoc is trying to commit to main

### ISSUE THREAD

**Issue by benlubas** [nvimtools/hydra.nvim#11]
seems like we need to tell it not to do that.. will look at it

**Comment by miversen33** [comment]
This seems correct? I don't know much about the gh pipeline but it makes sense that panvimdoc would add a commit to main to update vimdoc after any merge into main

**Comment by benlubas** [comment]
currently it's running in the PRs and adding to them. The vimdoc changes then get merged with the rest of the PR. And then it tries to run in main, and fails b/c it doesn't have permission I think b/c it's a protected branch.

**Comment by miversen33** [comment]
Ahh gotcha, that makes sense. In theory then we should be able to move the doc generation up the pipeline _before_ it's merged onto main (I assume this is what you are looking into). Alternatively, I imagine there is a way to allow a bot to have direct write access to a protected branch in github

**Comment by benlubas** [comment]
> move the doc generation up the pipeline

It's already running in PRs, you can see it committed to the PR that I added it in
