### ISSUE TITLE
release-please needs more permissions

### ISSUE THREAD

**Issue by benlubas** [nvimtools/hydra.nvim#13]
@mochaaP I think this needs to be done on an organizational level.

Here's what I see in `settings > actions > general` I need to change that greyed out setting so that gh actions can create pull requests.

<img width="811" alt="image" src="https://github.com/nvimtools/hydra.nvim/assets/56943754/be857a97-7084-47e3-8358-26c1d6a25eb2">

**Comment by mochaaP** [comment]
https://github.com/nvimtools/none-ls.nvim/blob/main/.github/workflows/docs.yml#L2-L3

Add this to the top of the workflow and it should be good to go.

**Comment by benlubas** [comment]
@mochaaP that permission is already there in the release-please yml file. I think you just need to go an click the setting box on github, or someone has to change the organization setting to allow for that, I'm not too familiar with this.

**Comment by mochaaP** [comment]
Done. ✅

**Comment by benlubas** [comment]
perfect, job ran. thank you!
