### ISSUE TITLE
vim-options could probably use an overhaul

### ISSUE THREAD

**Issue by miversen33** [nvimtools/hydra.nvim#16]
Looking the [vim-options](https://github.com/nvimtools/hydra.nvim/blob/main/lua/hydra/hint/vim-options.lua) file, it only allows for hard coded options and that seems like a poor decision. If we opened it up a bit, we could in theory allow for _any_ options to be displayed here instead of hard coded options only.

This would almost certainly require a setup function, which we have slightly discussed before.

Thought?

In my head, we could provide a way via initial configuration, to allow a user to specify a function to call and a shorthand to use in a string, and we could interpolate that just like is being done currently with vim-options.

Breaking this open would allow for more control to be given to end users, and more customization options as well.

**Comment by benlubas** [comment]
https://github.com/nvimtools/hydra.nvim#hint

`funcs` key lets you pass any function for any option.

Are you talking about auto generating these functions for different options?

**Comment by miversen33** [comment]
I'll have to tinker, `func` seems to do what I was thinking :) IIRC you went down this "rabbit hole" a bit ago so I assume you know the right way of doing this.

Basically I wanted to be able to do arbitrary `%{}` variables in my hints and ended up digging through vim-options lol

**Comment by benlubas** [comment]
Yup, funcs allows you to do that

**Comment by miversen33** [comment]
Closing this out then :)
