### ISSUE TITLE
More Robust Dynamic Hints

### ISSUE THREAD

**Issue by benlubas** [nvimtools/hydra.nvim#2]
Currently dynamic hints exist for the options hydra, this is a really nice feature, but currently it's not very extensible. You have to use hard coded functions, limiting users to dynamic values that have already been included in the plugin. This is both limiting for users, and a burden on maintainers.

This issue will track the progress for replacing this system with something much more powerful, allowing users to create their own dynamic values.

**Comment by benlubas** [comment]
wait these already exist too. The readme needs an overhaul at some point... That's quite the task

**Comment by miversen33** [comment]
> wait these already exist too. The readme needs an overhaul at some point... That's quite the task

I absolutely agree. Documentation is not this projects strong suit. Can you share whatever config options you found for this?

**Comment by benlubas** [comment]
Yup, it's the `funcs` field in `config.hint`

```lua
Hydra({
  -- ... other config
  hint = "%{txtw} textwidth" -- evaluates to "[ ] textwidth" or "[x] textwidth"
  config = {
    hint = {
      funcs = {
        ["txtw"] = function()
          if vim.o.textwidth == 0 then
            return "[ ]"
          else
            return "[x]"
          end
        end
      }
    },
  },
})
```
