### ISSUE TITLE
Thoughts on toggleable hydra hint windows

### ISSUE THREAD

**Issue by miversen33** [nvimtools/hydra.nvim#24]
I don't know how difficult this work effort is and I am likely going to explore it regardless of the response to this request.

That said, I am toying with using hydra to "set" more vim modes. Stuff like "dap" mode or "lsp" mode (whatever else I come up with). Basically you can toggle new modes and let the hydra handle those keybindings. I already basically do this with pink hydras right now, but I am looking at trying to hide the hint window unless its prompted for. 

Have you @benlubas been down this rabbit hole before? Do you have thoughts on this?

**Comment by benlubas** [comment]
My immediate thought is this probably isn't too hard to do, but I haven't looked into it

**Comment by miversen33** [comment]
Closing as #25 is complete
