### ISSUE TITLE
Deprecation Warnings should only be shown, when a deprecated option is really used

### ISSUE THREAD

**Issue by seflue** [nvimtools/hydra.nvim#40]
Hydra.nvim annoys me at every startup with a deprecation warning about "hint.border" which I actually don't use. After a short look at the code I think, it actually pretends to only warn about used options, but I clearly have already migrated it to `hint.float_opts.border`. And even if I remove it completely from my config I still get the warning.

**Comment by benlubas** [comment]
I've used Hydra since the deprecations were added and don't see the deprecation message.

When looking at the code were able to determine why this happens? 

Otherwise this seems like a config problem.
