### ISSUE TITLE
Toggle hydra autocmd,  with dap - hide on BufEnter...

### ISSUE THREAD

**Issue by JoseConseco** [nvimtools/hydra.nvim#41]
When debugging it is really annoying when u cant edit and see what is going on in dap eval window - since it is convered by hydra:
![image](https://github.com/nvimtools/hydra.nvim/assets/13521338/1bbf997b-e65f-4876-bcbf-8f520f0f930b)

I have autocommand that fixes it: on 'BuffEnter' event - if new entered buffer type, is not same as debugged one (eg. if we leave python buffer - and jump to dap eval buffer) - it would hide  Hydra. then when jumping back to  python file - it would show it.  The code itself still works, but since jumping to this fork,   using  'dap.step_over()' ( 'n' key in my setup below) - hydra will break and throw error:
![image](https://github.com/nvimtools/hydra.nvim/assets/13521338/770cd2c7-203d-4755-8a0d-ef0953a9de39)
If I do not use 'dap.step_over()' then hydra dynamic hiding, when jumping over buffers, still works.

Any idea how to re-implement dynamic hiding - or this is bug in hydra? script below worked 2-3 months ago..

My quick debugging:
The `vim.api.nvim_buf_is_valid(opts.buf)' shows that buffer '97' is valid (even though error says otherwise) 

        if dap_hydra then
          print("Exit dap hydra")
          dap_hydra:exit()   -- error  seems to be  happen here, since 'exit dap hydra' is printed ok... - but only on dap.step()
        end

```lua
local function show_dap_hydra()
  dap_hydra = Hydra {
    hint = hint,
    config = {
      color = "pink",
      invoke_on_body = true,
      -- buffer = 0,  -- only for active buffer
      desc = "Dap Hydra",
      hint = {
        position = "bottom",
        float_opts = { border = 'rounded' }
      },
    },
    name = "Dap",
    mode = { "n", "x", "v" },
    body = "<leader>dh",
    heads = {
      { "s", dap.continue, { silent = true } },
      { "X", dap.close, { silent = true } }, -- close current session (This does NOT terminate the debug adapter or debugee. - for that use |dap.terminate()| or |dap.disconnect()|)
      { "b", dap.toggle_breakpoint, { silent = true } },
      { "B", cond_breakpoint, { silent = true } },
      { "L", log_breakpoint, { silent = true } },
      -- { "R", dap.repl.open, { silent = true } },
      -- { "K", ":lua require('dap.ui.widgets').hover()<CR>", { silent = true } },
      { "K", eval_with_visual_selection, { silent = true } },

      { "n", dap.step_over, { silent = true } },
      { ">", dap.step_into, { silent = true } },
      { "<", dap.step_out, { silent = true } },
      { "c", dap.run_to_cursor, { silent = true } },
      { "x", ":lua require'dap'.disconnect({ terminateDebuggee = false })<CR>", { exit = true, silent = true } },
      { "C", ":lua require('dapui').close()<cr>:DapVirtualTextForceRefresh<CR>", { silent = true } },
      -- { 'K', ":lua require('dapui').eval(nil, {enter=true})<CR>", { silent = true } },
      -- { 'B', function() gitsigns.blame_line{ full = true } end },
      { "q", nil, { exit = true, nowait = true } },
    },
  }

  dap_ft = vim.bo.filetype
  dap_hydra:activate()
end

-- local hydra_visible = false
Hydra.spawn = Hydra.spawn or {}
Hydra.spawn["dap_hydra"] = function()
  show_dap_hydra()

  -- somehow code below errors out on invalid target buffer- even thoug seems valid.., ond :exit()
  vim.api.nvim_create_autocmd({ "BufEnter" }, {
    pattern = "*",
    callback = function(opts)
      print("BufEnter: buf " .. opts.buf .. " valid: " .. tostring(vim.api.nvim_buf_is_valid(opts.buf)))
      print("BufEnter: filetype " .. vim.bo[opts.buf].filetype .. " dap_ft: " .. dap_ft)
      -- print("Is visible: " .. tostring(hydra_visible))
      print("dap_hydra: " .. tostring(dap_hydra))
      if dap.session() == nil then
        return true -- close autocmd
      end
      if vim.api.nvim_buf_is_valid(opts.buf) and vim.bo[opts.buf].filetype == dap_ft then
        print("Show dap")
        show_dap_hydra()
      else
        if dap_hydra then
          print("Exit dap hydra")
          dap_hydra:exit()
        end
      end
      -- return true -- finish au
    end,
    group = dap_au_group,
  })
end

dap.listeners.before.event_initialized["hydra_integration"] = function(session, body)
  print("Started", vim.inspect(session), vim.inspect(body))
  dap.set_breakpoint()
  require("hydra").spawn["dap_hydra"]()
end
dap.listeners.before.event_exited["hydra_integration"] = function(session, body)
  print("Started", vim.inspect(session), vim.inspect(body))
  dap.set_breakpoint()
  require("hydra").spawn["dap_hydra"]()
end

```

**Comment by JoseConseco** [comment]
And my quick debug output:
![image](https://github.com/nvimtools/hydra.nvim/assets/13521338/6cad16b7-2dd7-4711-9c76-04781e3aab7b)

**Comment by benlubas** [comment]
This is probably an issue where we don't set the hint window to non focusable anymore bc that part of the code did change a little bit a while ago. I can look into it right now but I can take a look late tonight or tomorrow morning.

**Comment by benlubas** [comment]
Sorry that took me so long, was a little busy. 

We already set `focusable = false` on all the hint windows. It seems like dap or dap UI are using `nvim_set_current_win` which can ignore `focusable`. To me, this seems like unexpected behavior in DAP/DAP UI.

**Comment by JoseConseco** [comment]
Ok,  I will create new issues there then. Thanks for the feedback. Closing this.
