### ISSUE TITLE
Pink hydra breaks in nightly

### ISSUE THREAD

**Issue by Cathyprime** [nvimtools/hydra.nvim#46]
after bisecting, this change is the reason for breakage: neovim/neovim@3a881132460430d23f2fdc87822c87d47f721cfc

stacktrace:
```
vim/shared.lua:0: s: expected string, got number (1)

# stacktrace:
  - vim/shared.lua:0 _in_ **validate**
  - vim/shared.lua:0 _in_ **startswith**
  - vim/_init_packages.lua:0 _in_ **__index**
  - vim/shared.lua:0 _in_ **islist**
  - vim/shared.lua:0 _in_ ****
  - vim/shared.lua:0 _in_ **tbl_deep_extend**
  - /hydra.nvim/lua/hydra/layer/init.lua:116 _in_ **initialize**
  - /hydra.nvim/lua/hydra/lib/class.lua:14 _in_ **Layer**
  - /hydra.nvim/lua/hydra/init.lua:440 _in_ **_setup_pink_hydra**
  - /hydra.nvim/lua/hydra/init.lua:282 _in_ **initialize**
  - /hydra.nvim/lua/hydra/lib/class.lua:14
  - ~/.config/nvim/lua/cathy/plugin/debug.lua:130 _in_ **config**
```

for completeness this is the referenced line in config: https://github.com/Cathyprime/nvim-dots/blob/63603e94b5ed99265ce728dc4bc7168308b9406e/lua/cathy/plugin/debug.lua#L130-L151

and this also breaks: https://github.com/Cathyprime/nvim-dots/blob/63603e94b5ed99265ce728dc4bc7168308b9406e/lua/cathy/plugin/debug.lua#L165-L207

the code works in neovim/neovim@08153ddd1c149c867948f4681846531d53ba7759

edit: most likely the [HACK](https://github.com/nvimtools/hydra.nvim/blob/7f5341643107d05a8d7d4fdea00b29af28517380/lua/hydra/layer/init.lua#L108-L118) has failed

**Comment by benlubas** [comment]
Nightly is doing some... interesting things right now. I'm not going to support nightly right now b/c they seem to want to make massive breaking changes.

If this is still an issue closer to 0.11.0, please reopen

**Comment by Cathyprime** [comment]
sure thing :)

for people looking for temporary nightly support use my fork (change back when 0.11 releases as I have 0 plans to maintain that)
