### ISSUE TITLE
README overhaul

### ISSUE THREAD

**Issue by benlubas** [nvimtools/hydra.nvim#5]
I'm willing to take this on, possibly tomorrow. There's a few main things that I want to do:

- Keep the intro b/c it's absolutely amazing, whoever wrote that for the original emacs hydra... hats off to ya
- Completely remove the examples, and put them in the wiki instead. Point to the wiki from the README
- Majorly re-write the `Hydra({})` documentation... It's currently very hard to navigate, easy to get lost in, and hard to see what's important. 
- Potentially reorganize some of the other parts

**Comment by miversen33** [comment]
Writing documentation is hard, godspeed lol.

I would highly advise we do this in sections, and a primary goal here would be that the readme can be easily converted to vimdoc. Anything that doesn't really fit in the vim help should, IMO be migrated to the wiki (with links as needed in the README).
