### ISSUE TITLE
vim/shared.lua:0: s: expected string, got number hydra

### ISSUE THREAD

**Issue by CarlosGT7274** [nvimtools/hydra.nvim#56]
vim/shared.lua:0: s: expected string, got number hydra

Failed to run `config` for multicursors.nvim

vim/shared.lua:0: s: expected string, got number

# stacktrace:
  - vim/shared.lua:0 _in_ **validate**
  - vim/shared.lua:0 _in_ **startswith**
  - vim/_init_packages.lua:0 _in_ **__index**
  - vim/shared.lua:0 _in_ **islist**
  - vim/shared.lua:0 _in_ ****
  - vim/shared.lua:0 _in_ **tbl_deep_extend**
  - /hydra.nvim/lua/hydra/layer/init.lua:116 _in_ **initialize**
  - /hydra.nvim/lua/hydra/lib/class.lua:14 _in_ **Layer**
  - /hydra.nvim/lua/hydra/init.lua:440 _in_ **_setup_pink_hydra**
  - /hydra.nvim/lua/hydra/init.lua:282 _in_ **initialize**
  - /hydra.nvim/lua/hydra/lib/class.lua:14 _in_ **Hydra**
  - /multicursors.nvim/lua/multicursors/layers.lua:196 _in_ **create_normal_hydra**
  - /multicursors.nvim/lua/multicursors/init.lua:108 _in_ **setup**

**Comment by miversen33** [comment]
Please understand that without providing any sort of useful information, this issue cannot be resolved.

We would need to know at least the following

1) What version of neovim are you running?
2) What version of Hydra.nvim are you using?
3) What configuration did you use with Hydra to reproduce this?

Simply dropping a stack trace into an issue and saying "help" is as useful as not opening an issue.

**Comment by miversen33** [comment]
Additionally, looking at the stack, have you considered checking [multicursors.nvim](https://github.com/smoka7/multicursors.nvim) which is where your error is coming from?

Namely, [#104](https://github.com/smoka7/multicursors.nvim/issues/104)?

**Comment by miversen33** [comment]
@JohnWilliston 

Just to be clear, your configuration you provided refers to `anuvyklack/hydra.nvim`

You're certain you reproduced this issue with this fork?

**Comment by JohnWilliston** [comment]
Yes, @miversen33, I am using that fork. Maybe I shouldn't be. I basically tried the Hydra plugin because a friend showed me how much easier it makes adding breakpoints, toggling options, etc.

**Comment by miversen33** [comment]
To avoid confusion, let me reframe my question

The configuration you provided is using [**the original version of this project**](https://github.com/anuvyklack/hydra.nvim)

That version appears to be orphaned, and thus this fork was born. If you are seeing the above error while using the configuration you provided, you are _not_ using this plugin, you are using the original.

All of that said, please also read this issue. You are using `Neovim v0.11.0-dev-1344+g17383870dd` which is the dev version of Neovim. [We are currently waiting for neovim dev to settle down before addressing issues related to neovim dev](https://github.com/nvimtools/hydra.nvim/issues/49)

If you update your configuration to point to the correct repo (assuming the configuration you provided is the config you are using), and use the most recent neovim stable, I suspect the error disappears

**Comment by JohnWilliston** [comment]
Aha! Thank you for pointing me in that direction. I built from source the version of Neovim I was using in that Ubuntu 22.04 distro because the versions available from package managers were maybe 0.6 or older. I took the time to get the latest stable Neovim 0.10.4 installed, and that solved the issue. Thanks for that and the clarification as well.
